square_config:
  total_cards: 4
  concurrency: 4
  sleepy_time: 0
  standard_deviation_powerLevel: 0.5
  power_level_rarity_skew: 0.4 # in [0,1] Adjust this value to skew the power level based on rarity 
  output_dir: "output" # Directory to save generated cards
http_config:
  timeout: 60
  retries: 3
  retry_delay: 20
mtgcg_mse_config:
  image_method: "download" # opions: none, localSD, download
SD_config:
  max_tag_weight: 2.5
  forge_url_base: "http://127.0.0.1:7860"
  sd_output_dir: "forge-out"
  random_lora_weights: true # Set to true to use random weights for Loras
  lora_weight_standard_deviation: 0.35 # Standard deviation for Lora weights
  apply_lora_chance: 50 # Chance to skip Lora application
  use_special_tags: true # Set to true to use special tags in prompts
  varying_special_tags_weight: true # Set to true to vary special tags weights
  model_swap_chance: 66 # Chance to change model for each card (0-100)
  randomise_negative_prompt: true # Set to true to use negative prompts
  chance_no_negative_prompt: 50 # Chance to not use negative prompt
  special_tags:
    Fantasy World:
      weight: 1.2
      chance: 100
    NSFW:
      weight: 1.5
      chance: 5
    Gore:
      weight: 1.5
      chance: 5
    Porn:
      weight: 1.5
      chance: 5
    Hentai:
      weight: 1.5
      chance: 5
  image_options:
    - name: FLUX
      weight: 10.0
      option_params:
        model: FLUX1DEV_HYPERNF4_FLUX1DEVBNB_FLUX1DEVHYPERNF4 # enum NAME
        loras:
          FantasyWorldPonyV2: 0.1
          fantasyV1.1: 0.1
          dungeons_and_dragons_xl_v3: 0.1
          Dark_Fantasy_1.5_IL: 0.1
        steps: 24
        cfg_scale: 1
        distilled_cfg_scale: 3.5
        width: 1024
        height: 748
        sampler_name: Euler
        scheduler: Simple
        seed: -1
        n_iter: 1
        batch_size: 1
    - name: PILLU
      weight: 1.0
      option_params:
        model: PREFECT_ILLUSTRIOUS_XL_V20P
        loras:
          FantasyWorldPonyV2: 0.1
          fantasyV1.1: 0.1
          dungeons_and_dragons_xl_v3: 0.1
          Dark_Fantasy_1.5_IL: 0.85
        steps: 128
        cfg_scale: 5
        sampler_name: "DPM++ 2M SDE"
        scheduler: Simple
        width: 1024
        height: 748
        seed: -1
        n_iter: 1
        batch_size: 1
    - name: PEPONY
      weight: 0.5
      option_params:
        model: PREFECT_PONY_XL_V50
        loras:
          FantasyWorldPonyV2: 0.85
          fantasyV1.1: 0.1
          dungeons_and_dragons_xl_v3: 0.1
          Dark_Fantasy_1.5_IL: 0.1
        steps: 128
        cfg_scale: 5
        sampler_name: "DPM++ 2M SDE"
        scheduler: Simple
        width: 1024
        height: 748
        seed: -1
        n_iter: 1
        batch_size: 1
        negative_prompt: "blurry, low quality, watermark, text, signature, cropped, extra limbs, disfigured, bad anatomy"
    - name: REDREAM
      weight: 1.0
      option_params:
        model: REAL_DREAM_SDXL_PONY15
        loras:
          FantasyWorldPonyV2: 0.1
          fantasyV1.1: 0.85
          dungeons_and_dragons_xl_v3: 0.1
          Dark_Fantasy_1.5_IL: 0.1
        steps: 128
        cfg_scale: 5
        sampler_name: "DPM++ 2M SDE"
        scheduler: Simple
        width: 1024
        height: 748
        seed: -1
        n_iter: 1
        batch_size: 1
        negative_prompt: "blurry, low quality, watermark, text, signature, cropped, extra limbs, disfigured, bad anatomy"
    - name: REALISM_YOGI
      weight: 0.5
      option_params:
        model: REALISM_BY_STABLE_YOGI_V40FP16
        loras:
          FantasyWorldPonyV2: 0.1
          fantasyV1.1: 0.1
          dungeons_and_dragons_xl_v3: 0.1
          Dark_Fantasy_1.5_IL: 0.85
        steps: 128
        cfg_scale: 5
        sampler_name: "DPM++ 2M SDE"
        scheduler: Simple
        width: 1024
        height: 748
        seed: -1
        n_iter: 1
        batch_size: 1
        negative_prompt: "blurry, low quality, watermark, text, signature, cropped, extra limbs, disfigured, bad anatomy"
    - name: UNSTABLE_DIFFUSERS
      weight: 2.0
      option_params:
        model: SDXL_UNSTABLE_DIFFUSERS_V9_DIVINITYMACHINEVAE
        loras:
          FantasyWorldPonyV2: 0.1
          fantasyV1.1: 0.1
          dungeons_and_dragons_xl_v3: 0.85
          Dark_Fantasy_1.5_IL: 0.1
        steps: 128
        cfg_scale: 5
        sampler_name: "DPM++ 2M SDE"
        scheduler: Simple
        width: 1024
        height: 748
        seed: -1
        n_iter: 1
        batch_size: 1
        negative_prompt: "blurry, low quality, watermark, text, signature, cropped, extra limbs, disfigured, bad anatomy"
    - name: WAI_NSFW_ILLUSTRIOUS
      weight: 1
      option_params:
        model: WAI_NSFW_ILLUSTRIOUS_V110
        loras:
          FantasyWorldPonyV2: 0.85
          fantasyV1.1: 0.1
          dungeons_and_dragons_xl_v3: 0.1
          Dark_Fantasy_1.5_IL: 0.1
        steps: 128
        cfg_scale: 5
        sampler_name: "DPM++ 2M SDE"
        scheduler: Simple
        width: 1024
        height: 748
        seed: -1
        n_iter: 1
        batch_size: 1
        negative_prompt: "blurry, low quality, watermark, text, signature, cropped, extra limbs, disfigured, bad anatomy"
set_params:
  set: "Null Revelation"
  themes:
    - "No cards in hand"
    - "Emptiness and void"
    - "Zen"
    - "Forgotten Echoes"
    - "Oblivion Cult"
    - "Ascetic Wanderers"
    - "Lotus Spirit"
    - "Solitude"
    - "The silence after the storm has passed, when only memories remain"
    - "Echoes of a world lost to time, where nothing remains but dust"
    - "Stillness"
    - "The last candle flickering in endless darkness"
api_params:
  generate_image_prompt: false
  creative: false
  include_explanation: false
  image_model: "dall-e-3" # dall-e-3,dall-e-2, none
  model: "gpt-41"
skeleton_params:
  power_level: 6 # Power level of the card, 1-10 or None
  wildcard_supertype: false
  fixed_amount_themes: 0 # if not zero, will select a fixed amount of themes from the available ones instead of mutating them randomly
  mutation_chance_per_theme: 12.5 # Chance to mutate each theme, ignored if fixed_amount_themes is not zero
  colors: ["white", "blue", "black", "red", "green", "colorless"]
  colors_weights:
    white: 15
    blue: 15
    black: 15
    red: 15
    green: 15
    colorless: 10
  card_types_weights:
    _default:
      creature: 40
      planeswalker: 3
      instant: 15
      sorcery: 15
      enchantment: 10
      saga: 2
      battle: 2
      land: 10
      basic land: 3
      artifact: 0
      artifact creature: 0
      kindred: 0
    white:
      creature: 55
      land: 8
    colorless:
      artifact: 70
      "artifact creature": 30
  function_tags:
    ramp or mana fixing: 15
    draw or card advantage: 15
    removal or control: 10
    No cards in hand payoff: 35
    No cards in hand enabler: 35
    board wipe or mass removal: 5
    activated ability: 5
    Flying or other evasion: 5
    simple or straightforward: 10
  tags_maximum: 3 # Default is null, which means no limit
