square_config:
  total_cards: 60
  concurrency: 4
set_params:
  set: "Monkeys in Space"
  themes:
    - "Space"
    - "Monkeys"
    - "Chaos"
    - "Adventure"
    - "Exploration"
    - "Surrealism"
    - "Absurdity"
    - "Humor"
    - "Intergalactic"
    - "Futurism"
skeleton_params:
  power_level: 7.5 # Power level of the card, 1-10 or None
  wildcard_supertype: false
  fixed_amount_themes: 0 # if not zero, will select a fixed amount of themes from the available ones instead of mutating them randomly
  mutation_chance_per_theme: 12.5 # Chance to mutate each theme, ignored if fixed_amount_themes is not zero
  colors: ["green", "red", "colorless"]
  colors_weights:
    green: 55
    red: 25
    colorless: 10
  card_types_weights:
    _default:
      kindred: 0
      creature: 45
      land: 20
      basic land: 20
  function_tags:
    ramp or mana fixing: 15
    draw or card advantage: 5
    removal or control: 10
    apes together strong: 40
    banana token or counter: 20
    coconut token or counter: 20
    board wipe or mass removal: 5
    activated ability: 5
    Flying or other evasion: 5
    simple or straightforward: 10
  tags_maximum: 2 # Default is null, which means no limit
