skeleton_params:
  card_types_weights:
    _default:
      creature: 80.0
      planeswalker: 5.0
      enchantment: 3.8
      basic land: 0.0
      artifact creature: 0.0
      land: 3.8
      artifact: 0.0
      instant: 3.8
      sorcery: 3.8
      saga: 0.0
      kindred: 0.0
      battle: 0.0
    white:
      creature: 70.0
      instant: 20.0
      sorcery: 5.0
      enchantment: 1.5
      basic land: 0.0
      planeswalker: 2.0
      artifact creature: 0.0
      land: 1.5
      artifact: 0.0
      saga: 0.0
      kindred: 0.0
      battle: 0.0
  colors_weights:
    white: 50.0
    blue: 50.0
  card_types:
  - creature
  - artifact creature
  - planeswalker
  - instant
  - sorcery
  - enchantment
  - saga
  - battle
  - land
  - basic land
  - artifact
  - kindred
