skeleton_params:
  # Missing colors_weights - will use defaults (warning)
  
  card_types_weights:
    _default:
      creature: 60.0
      instant: 40.0
      # Missing other types - partial logic will handle
    
    white:
      creature: 90.0
      enchantment: 10.0
      # Missing other types
  
  generations: 500  # High but valid (warning)
  threads: 8        # Reasonable
