skeleton_params:
  colors_weights:
    white: 20.0
    blue: 20.0
    black: 20.0
    red: 20.0
    green: 20.0
  
  card_types_weights:
    _default:
      creature: 70.0
      instant: 20.0
      sorcery: 5.0
      # Missing types: enchantment, artifact, planeswalker, etc.
    
    red:
      creature: 80.0
      instant: 10.0
      # Missing types: sorcery, artifact, etc.
