square_config:
  total_cards: 5

set_params:
  set: "Edge Case Test"
  themes: ["Testing"]

skeleton_params:
  colors: ["white", "blue", "red"]
  colors_weights:
    white: 33.33
    blue: 33.33
    red: 33.34
  
  # Edge case: mix of zeros, very small values, and normal values
  card_types_weights:
    _default:
      creature: 0.0        # Explicit zero
      instant: 0.1         # Very small value
      sorcery: 99.9        # Large value
      # Missing: artifact, land, etc. (should be filled)
    
    # Edge case: User provides exactly 100% 
    white:
      creature: 50.0
      instant: 25.0
      sorcery: 25.0
      # No other types - total is exactly 100%
    
    # Edge case: User provides way over 100%
    blue:
      creature: 80.0
      instant: 50.0
      sorcery: 30.0
      # Total = 160%, should normalize everything
    
    # Edge case: Only zeros
    red:
      creature: 0.0
      instant: 0.0
      sorcery: 0.0
      # Everything else should be filled from defaults
